theme: jekyll-theme-hacker
name: Kousik Nandy
title: Kousik Nandy
markdown: kramdown
description: My karma and collection of different hacks ...
excerpt_separator: <!--more-->
google_analytics: UA-101479508-1
