theme: jekyll-theme-hacker
name: Teach Machines
title: Teach Machines
markdown: kramdown
description: The mission of "Teach Machines" to simplify human life by applying Machine Learning to everyday problems
excerpt_separator: <!--more-->

