name: Kousik Nandy
title: Kousik Nandy
author: Kousik Nandy
description: My karma and collection of different hacks ...

avatar: "/assets/img/kousik_nandy_graffiti2.png"
social-network-links:
  email: "kousik.nandy@gmail.com"
  github: kousiknandy
  twitter: kousik
  linkedin: kousiknandy
  
markdown: kramdown
excerpt_separator: <!--more-->
url-pretty: "kousiknandy.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false
highlighter: rouge
permalink: /:year-:month-:day-:title/

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-paginate
  - jekyll-sitemap
